image:
  registry: <ACCOUNT>.dkr.ecr.us-east-1.amazonaws.com
  repository: shrinkr
  tag: "" # set per-deploy via --set image.tag=$GIT_SHA

api:
  replicaCount: 4
  service:
    type: LoadBalancer
    port: 80
    targetPort: 8080
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 512Mi

worker:
  replicaCount: 3
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi

config:
  httpPort: "8080"
  redisAddr: "shrinkr.xxxxx.cache.amazonaws.com:6379"
  awsRegion: "us-east-1"
  baseShortUrl: "https://shrinkr.example.com"
  shortCodeBytes: "7"
