apiVersion: v1
kind: Secret
metadata:
  name: shrinkr-secrets
type: Opaque
stringData:
  POSTGRES_DSN: "postgres://shrinkr:shrinkr@postgres:5432/shrinkr?sslmode=disable"
  REDIS_PASSWORD: ""
  SQS_QUEUE_URL: "http://localstack:4566/000000000000/shrinkr-clicks"
  AWS_ACCESS_KEY_ID: "test"
  AWS_SECRET_ACCESS_KEY: "test"
