apiVersion: v1
kind: Secret
metadata:
  name: shrinkr-secrets
type: Opaque
stringData:
  POSTGRES_DSN: "postgres://shrinkr:shrinkr@postgres:5432/shrinkr?sslmode=disable"
  REDIS_PASSWORD: ""
  SQS_QUEUE_URL: ""
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
