apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "url-shortener.fullname" . }}-config
  labels:
    {{- include "url-shortener.labels" . | nindent 4 }}
data:
  HTTP_PORT: {{ .Values.config.httpPort | quote }}
  REDIS_ADDR: {{ .Values.config.redisAddr | quote }}
  AWS_REGION: {{ .Values.config.awsRegion | quote }}
  BASE_SHORT_URL: {{ .Values.config.baseShortUrl | quote }}
  SHORT_CODE_BYTES: {{ .Values.config.shortCodeBytes | quote }}
