apiVersion: v1
kind: Secret
metadata:
  name: {{ include "url-shortener.fullname" . }}-secrets
  labels:
    {{- include "url-shortener.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_DSN: {{ .Values.secrets.postgresDsn | quote }}
  REDIS_PASSWORD: {{ .Values.secrets.redisPassword | quote }}
  SQS_QUEUE_URL: {{ .Values.secrets.sqsQueueUrl | quote }}
  AWS_ACCESS_KEY_ID: {{ .Values.secrets.awsAccessKeyId | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.secrets.awsSecretAccessKey | quote }}
